### ISSUE TITLE
Support service[apache2] graceful instead of reload in web_app definition

### ISSUE THREAD

**Issue by runwaldarshu** [sous-chefs/apache2#160]
In general it will be nice to have graceful option in apache2 service provided by this cookbook which can be used by consumers.

Specific issue seen:
While doing some testing I have found that using service reload have some downtime on RHEL 6.5 httpd service. Whenever there are changes in configuration using web_app definition we would like it to call service graceful instead of reload so that we have no server downtime.

If it is not possible to add graceful option instead of reload in web_app https://github.com/onehealth-cookbooks/apache2/blob/master/definitions/web_app.rb#L40 at least provide a way to configure the action so that user can skip this action by setting it to none and then handle the reload/graceful on their end.

In general it will be nice to use graceful instead of reload if possible. Or at the least provide a way to ovrride or configure that option by consumer cookbooks if needed

**Comment by bbaja42** [comment]
Sorry for commenting on old merged issue:

I noticed that reload command was replaced with graceful.

Since graceful actually performs the restart, then what is the purpose of having both graceful and restart command, why not do graceful always?

**Comment by drpebcak** [comment]
@bbaja42 depending on what platform you are referring to, there is a difference between restart and graceful - basically, [this](https://teckadmin.wordpress.com/2013/10/23/difference-between-graceful-restart-and-normal-restart/).

**Comment by svanzoest** [comment]
This the section in the docs on the difference between restart and graceful.
http://httpd.apache.org/docs/current/stopping.html


On May 12, 2017 09:19, "Taylor Price" <notifications@github.com> wrote:

@bbaja42 <https://github.com/bbaja42> depending on what platform you are
referring to, there is a difference between restart and graceful -
basically, this
<https://teckadmin.wordpress.com/2013/10/23/difference-between-graceful-restart-and-normal-restart/>
.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/sous-chefs/apache2/issues/160#issuecomment-301121566>,
or mute the thread

**Comment by bbaja42** [comment]
Cool, thnx
