### ISSUE TITLE
conf / site ressources fail if apache_dir/conf-available / site-available doesn't exist in a utility cookbook

### ISSUE THREAD

**Issue by bplessis** [sous-chefs/apache2#620]
# Brief Description

I'm trying to update my setup from my modified 3.1 cookbook to the latest 7.x release.
I have a main wrapper cookbook that is in charge of setting up apache using "apache2_install", but i also have another cookbook which is there to deploy and doing a minimalistic setup of the application server.

The utility cookbook want to define an apache2 configuration file and it fail because in my test environment the /etc/apache2 folder has been removed prior to the run.

## Cookbook version

7.0.0

## Chef-client version

14.11.21

## Platform Details

debian/stretch

## Scenario

[What you are trying to achieve and you can't?]

## Steps to Reproduce

  * rm/mv /etc/apache2 
  * run chef-client with a cookbook that only want to create an apache2 conf file

## Expected Result

resource should create/check the directory tree as needed

**Comment by damacus** [comment]
This wasn't done due to the package or compile step creating this for us usually. 

For example we always start of every clean kitchen run without an `/etc/apache2` directory. 

That said we always run `apache2_install` to manage this directory, we never run any of the config resource by itself. For your case your best bet might be to include the apache2 helpers in your recipe and create the directory with the directory resource
